## YAML Template.
---
# HTTP Server
server:
  port: 8092   # HTTP (Tomcat) port

# Spring properties
spring:
  application:
     name: eventmicroservice

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
